### ISSUE TITLE
Upgrade to Node 10 execution handler

### ISSUE THREAD

**Issue by zac-jacobson** [geeklearningio/gl-vsts-tasks-yarn#102]
Before opening an issue please [read this](https://github.com/geeklearningio/gl-vsts-tasks-yarn/wiki/How-to-Report-an-issue).

# Are you reporting a bug or a feature request ?
* [ ] Bug
* [x] Feature request

# Description

Azure is giving this warning:

```
##[warning]This task uses Node 6 execution handler, which will be deprecated soon. If you are the developer of the task - please consider the migration guideline to Node 10 handler - https://aka.ms/migrateTaskNode10. If you are the user - feel free to reach out to the owners of this task to proceed on migration.
```
See https://aka.ms/migrateTaskNode10

# Reproduction

We are using these tasks in our Azure pipeline, for example:
```
- task: geeklearningio.gl-vsts-tasks-yarn.yarn-installer-task.YarnInstaller@3
  displayName: 'Use Yarn 1.22.5'
  inputs:
    versionSpec: 1.22.5
```
and
```
- task: geeklearningio.gl-vsts-tasks-yarn.yarn-task.Yarn@3
  displayName: 'Yarn install'
  inputs:
    Arguments: 'install'
```

# System information

**VSTS or TFS:**
* [x] VSTS
* [ ] TFS

**Agent:**
* [x] Hosted
* [ ] Custom

**OS:**
* [x] Windows
* [x] Mac
* [ ] Linux

**Yarn task** and **Yarn installer task** version:
3.0.1999

**Yarn version:**
*1.22.5*

**Node version:**
*16.5.0*
