### ISSUE TITLE
Please support repository authentication for Yarn 3+

### ISSUE THREAD

**Issue by DannyMeister** [geeklearningio/gl-vsts-tasks-yarn#115]
# Are you reporting a bug or a feature request ?
* [ ] Bug
* [x] Feature request

# Description

Yarn 3 does not use `.npmrc`, rather it uses `.yarnrc.yml`.  Though our ADO packages repository is specified in `npmRegistryServer`, the Yarn@3 task does not update the .yarnrc.yml with an ident token for the repository.

# Expected behavior

Running the install argument from Yarn task should update `.yarnrc.yml`, adding `npmAuthIdent`.

# System information

**VSTS or TFS:**
* [x] VSTS
* [ ] TFS

**Agent:**
* [x] Hosted
* [ ] Custom

**OS:**
* [ ] Windows
* [ ] Mac
* [x] Linux

**Yarn version:**
3.4.1

**Node version:**
16.17.0

**Comment by DannyMeister** [comment]
My current workaround is to also include an `.npmrc` file in my repo (having to dual maintain the registry URL in each file), use the `npmAuthenticate` task to update `.npmrc` with an auth token, then copy it to my `.yarnrc.yml` file with a bash script.

```yaml
  - task: npmAuthenticate@0
    inputs:
      workingFile: .npmrc

  - task: Bash@3
    inputs:
      targetType: "inline"
      script: |
        grep -m1 'npm/registry/:_authToken=' .npmrc | cut -f2- -d'=' | sed 's/\(.*\)/\nnpmAuthToken: \"\1\"/' >> .yarnrc.yml
    displayName: "Copy .npmrc auth to .yarnrc.yml"
```
