### ISSUE TITLE
Document how to use the plugin with Azure Pipelines defined in Yaml

### ISSUE THREAD

**Issue by tomasaschan** [geeklearningio/gl-vsts-tasks-yarn#53]
Since VSTS became Azure DevOps and launched the `azure-pipeline.yml` option for configuring builds and releases, there are multiple ways to use this task - you can either configure it with the web GUI, or in a yaml file in your repository. However, I can't find any documentation on the Yaml schema to use.

It probably comes down to something like

```yml
- task: Yarn@<version>
  <options here>
```

but it would be nice to have a reference spec for names of available options, their default values etc. One can look e.g. at the top of https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/tool/node-js?view=vsts for inspiration.

**Comment by Sawtaytoes** [comment]
```yml
steps:
- task: geeklearningio.gl-vsts-tasks-yarn.yarn-task.Yarn@2
  displayName: 'Yarn '
  inputs:
    ProductionMode: true
```

That's what it does.

**Comment by sandorfr** [comment]
You can see any build yaml equivalent : http://www.codewrecks.com/blog/index.php/2017/12/14/converting-regular-build-in-yaml-build/

Here are some samples:

```yaml
resources:
- repo: self
  clean: true
queue:
  name: Shared Windows
steps:
- task: geeklearningio.gl-vsts-tasks-yarn-dev.yarn-installer-task.YarnInstaller@2
  displayName: 'Use Yarn 1.9.x'
  inputs:
    versionSpec: 1.9.x

    checkLatest: true

    includePrerelease: true


- task: geeklearningio.gl-vsts-tasks-yarn-dev.yarn-task.Yarn@2
  displayName: 'No custom package no npmrc'
  inputs:
    ProjectDirectory: src/YarnNoNpmRc


- task: geeklearningio.gl-vsts-tasks-yarn-dev.yarn-task.Yarn@2
  displayName: 'No custom package but .npmrc'
  inputs:
    ProjectDirectory: src/YarnNpmRc


- task: geeklearningio.gl-vsts-tasks-yarn-dev.yarn-task.Yarn@2
  displayName: 'Custom Package in Custom Feed Directly Specified'
  inputs:
    ProjectDirectory: src/YarnCustomPackageNoNpmRc

    customRegistry: useFeed

    customFeed: '00000-0000-0000-0000-00000000'


- task: geeklearningio.gl-vsts-tasks-yarn-dev.yarn-task.Yarn@2
  displayName: 'Custom Package in Custom Feed npmrc'
  inputs:
    ProjectDirectory: src/YarnCustomPackageNpmRc


- task: geeklearningio.gl-vsts-tasks-yarn-dev.yarn-task.Yarn@2
  displayName: 'Yarn licenses generate-disclaimer'
  inputs:
    ProjectDirectory: src/SampleNode

    Arguments: 'licenses generate-disclaimer'

    customRegistry: useFeed

    customFeed: '00000-0000-0000-0000-00000000'

```
