### ISSUE TITLE
Unexpected token < in JSON at position 0

### ISSUE THREAD

**Issue by ecraig12345** [geeklearningio/gl-vsts-tasks-yarn#91]
## Are you reporting a bug or a feature request ?
* [x] Bug
* [ ] Feature request

## Description

`YarnInstaller` intermittently fails with `##[error]Unexpected token < in JSON at position 0` 

[Example build with failure](https://uifabric.visualstudio.com/fabricpublic/_build/results?buildId=182172&view=logs&j=51ea0740-f124-536d-f0ac-55829fd17f46&t=e01b4ef8-4938-58d6-6f8f-ce7b23c6e21b)

The failure is not at all consistent, but it seems to disappear for weeks at a time and then come back (but still only intermittently).

## Expected behavior

The task either succeeds, or fails with a meaningful error.

## Reproduction

Task configuration (found in [this template file](https://github.com/microsoft/fluentui/blob/master/.devops/templates/tools.yml)):
```yml
  - task: geeklearningio.gl-vsts-tasks-yarn.yarn-installer-task.YarnInstaller@3
    displayName: 'Use Yarn 1.19.x'
    inputs:
      versionSpec: 1.19.x
      checkLatest: true
      includePrerelease: false
```

[Overall pipeline yaml](https://github.com/microsoft/fluentui/blob/master/azure-pipelines.yml) 

[Pipeline in ADO](https://uifabric.visualstudio.com/fabricpublic/_build/results?buildId=182172)

Unfortunately, the failure is infrequent/random enough that we'd have to leave `System.Debug` enabled for a few hours or days, which is probably not feasible.

My guess is that the culprit is these lines, and that the server at `https://publicblobs.geeklearning.io/yarn/tarballsV2.json` is occasionally returning an HTML error page which obviously can't be parsed as JSON.
https://github.com/geeklearningio/gl-vsts-tasks-yarn/blob/35fe5acf94d51c414c3395bd633805e65093e711/Tasks/YarnInstaller/yarnToolInstallerTask.ts#L13-L18

## System information

**VSTS or TFS:**
* [x] VSTS
* [ ] TFS

**Agent:**
* [ ] Hosted
* [x] Custom

**OS:**
* [ ] Windows
* [ ] Mac
* [x] Linux

**Yarn version:** 
1.19.x

**Node version:**
12.18.4
